# CMake generated Testfile for 
# Source directory: /Users/danielding/euclid-engine
# Build directory: /Users/danielding/euclid-engine/build_debug
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[smoke]=] "/Users/danielding/euclid-engine/build_debug/smoketest")
set_tests_properties([=[smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;63;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[fen]=] "/Users/danielding/euclid-engine/build_debug/fen_test")
set_tests_properties([=[fen]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;67;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[perft_smoke]=] "/Users/danielding/euclid-engine/build_debug/perft_smoke")
set_tests_properties([=[perft_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;71;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[king_smoke]=] "/Users/danielding/euclid-engine/build_debug/king_smoke")
set_tests_properties([=[king_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;75;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[bishop_smoke]=] "/Users/danielding/euclid-engine/build_debug/bishop_smoke")
set_tests_properties([=[bishop_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;79;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[rook_smoke]=] "/Users/danielding/euclid-engine/build_debug/rook_smoke")
set_tests_properties([=[rook_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;83;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[queen_smoke]=] "/Users/danielding/euclid-engine/build_debug/queen_smoke")
set_tests_properties([=[queen_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;87;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[pawn_smoke]=] "/Users/danielding/euclid-engine/build_debug/pawn_smoke")
set_tests_properties([=[pawn_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;91;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[pin_smoke]=] "/Users/danielding/euclid-engine/build_debug/pin_smoke")
set_tests_properties([=[pin_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;95;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[incheck_smoke]=] "/Users/danielding/euclid-engine/build_debug/incheck_smoke")
set_tests_properties([=[incheck_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;99;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[do_undo_smoke]=] "/Users/danielding/euclid-engine/build_debug/do_undo_smoke")
set_tests_properties([=[do_undo_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;103;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[castle_smoke]=] "/Users/danielding/euclid-engine/build_debug/castle_smoke")
set_tests_properties([=[castle_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;107;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[perft_refs]=] "/Users/danielding/euclid-engine/build_debug/perft_refs")
set_tests_properties([=[perft_refs]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;111;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[eval_smoke]=] "/Users/danielding/euclid-engine/build_debug/eval_smoke")
set_tests_properties([=[eval_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;115;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[uci_smoke]=] "/Users/danielding/euclid-engine/build_debug/uci_smoke")
set_tests_properties([=[uci_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;119;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[search_smoke]=] "/Users/danielding/euclid-engine/build_debug/search_smoke")
set_tests_properties([=[search_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;123;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[search_limits_smoke]=] "/Users/danielding/euclid-engine/build_debug/search_limits_smoke")
set_tests_properties([=[search_limits_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;127;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[nullmove_state_smoke]=] "/Users/danielding/euclid-engine/build_debug/nullmove_state_smoke")
set_tests_properties([=[nullmove_state_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;131;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[draw_rules_smoke]=] "/Users/danielding/euclid-engine/build_debug/draw_rules_smoke")
set_tests_properties([=[draw_rules_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;135;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[encode_smoke]=] "/Users/danielding/euclid-engine/build_debug/encode_smoke")
set_tests_properties([=[encode_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;139;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[nn_smoke]=] "/Users/danielding/euclid-engine/build_debug/nn_smoke")
set_tests_properties([=[nn_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;143;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[nn_eval_integration_smoke]=] "/Users/danielding/euclid-engine/build_debug/nn_eval_integration_smoke")
set_tests_properties([=[nn_eval_integration_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;147;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[search_nn_pov_smoke]=] "/Users/danielding/euclid-engine/build_debug/search_nn_pov_smoke")
set_tests_properties([=[search_nn_pov_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;151;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[uci_evalmodel_smoke]=] "/Users/danielding/euclid-engine/build_debug/uci_evalmodel_smoke")
set_tests_properties([=[uci_evalmodel_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;155;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[nn_make_const_smoke]=] "/Users/danielding/euclid-engine/build_debug/nn_make_const_smoke")
set_tests_properties([=[nn_make_const_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;160;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[selfplay_smoke]=] "/Users/danielding/euclid-engine/build_debug/selfplay_smoke")
set_tests_properties([=[selfplay_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;164;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[eval_sanity_smoke]=] "/Users/danielding/euclid-engine/build_debug/eval_sanity_smoke")
set_tests_properties([=[eval_sanity_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;168;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[dataset_smoke]=] "/Users/danielding/euclid-engine/build_debug/dataset_smoke")
set_tests_properties([=[dataset_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;172;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
