# CMake generated Testfile for 
# Source directory: /Users/danielding/euclid-engine
# Build directory: /Users/danielding/euclid-engine/build_asan
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[smoke]=] "/Users/danielding/euclid-engine/build_asan/smoketest")
set_tests_properties([=[smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;50;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[fen]=] "/Users/danielding/euclid-engine/build_asan/fen_test")
set_tests_properties([=[fen]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;54;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[perft_smoke]=] "/Users/danielding/euclid-engine/build_asan/perft_smoke")
set_tests_properties([=[perft_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;58;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[king_smoke]=] "/Users/danielding/euclid-engine/build_asan/king_smoke")
set_tests_properties([=[king_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;62;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[bishop_smoke]=] "/Users/danielding/euclid-engine/build_asan/bishop_smoke")
set_tests_properties([=[bishop_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;66;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[rook_smoke]=] "/Users/danielding/euclid-engine/build_asan/rook_smoke")
set_tests_properties([=[rook_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;70;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[queen_smoke]=] "/Users/danielding/euclid-engine/build_asan/queen_smoke")
set_tests_properties([=[queen_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;74;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[pawn_smoke]=] "/Users/danielding/euclid-engine/build_asan/pawn_smoke")
set_tests_properties([=[pawn_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;78;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[pin_smoke]=] "/Users/danielding/euclid-engine/build_asan/pin_smoke")
set_tests_properties([=[pin_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;82;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[incheck_smoke]=] "/Users/danielding/euclid-engine/build_asan/incheck_smoke")
set_tests_properties([=[incheck_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;86;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[do_undo_smoke]=] "/Users/danielding/euclid-engine/build_asan/do_undo_smoke")
set_tests_properties([=[do_undo_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;90;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[castle_smoke]=] "/Users/danielding/euclid-engine/build_asan/castle_smoke")
set_tests_properties([=[castle_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;94;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[perft_refs]=] "/Users/danielding/euclid-engine/build_asan/perft_refs")
set_tests_properties([=[perft_refs]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;98;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[eval_smoke]=] "/Users/danielding/euclid-engine/build_asan/eval_smoke")
set_tests_properties([=[eval_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;102;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[uci_smoke]=] "/Users/danielding/euclid-engine/build_asan/uci_smoke")
set_tests_properties([=[uci_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;106;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[search_smoke]=] "/Users/danielding/euclid-engine/build_asan/search_smoke")
set_tests_properties([=[search_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;110;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[search_limits_smoke]=] "/Users/danielding/euclid-engine/build_asan/search_limits_smoke")
set_tests_properties([=[search_limits_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;114;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[nullmove_state_smoke]=] "/Users/danielding/euclid-engine/build_asan/nullmove_state_smoke")
set_tests_properties([=[nullmove_state_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;118;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[draw_rules_smoke]=] "/Users/danielding/euclid-engine/build_asan/draw_rules_smoke")
set_tests_properties([=[draw_rules_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;122;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[encode_smoke]=] "/Users/danielding/euclid-engine/build_asan/encode_smoke")
set_tests_properties([=[encode_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;126;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[nn_smoke]=] "/Users/danielding/euclid-engine/build_asan/nn_smoke")
set_tests_properties([=[nn_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;130;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[nn_eval_integration_smoke]=] "/Users/danielding/euclid-engine/build_asan/nn_eval_integration_smoke")
set_tests_properties([=[nn_eval_integration_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;134;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[search_nn_pov_smoke]=] "/Users/danielding/euclid-engine/build_asan/search_nn_pov_smoke")
set_tests_properties([=[search_nn_pov_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;138;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[uci_evalmodel_smoke]=] "/Users/danielding/euclid-engine/build_asan/uci_evalmodel_smoke")
set_tests_properties([=[uci_evalmodel_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;142;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[nn_make_const_smoke]=] "/Users/danielding/euclid-engine/build_asan/nn_make_const_smoke")
set_tests_properties([=[nn_make_const_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;147;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[selfplay_smoke]=] "/Users/danielding/euclid-engine/build_asan/selfplay_smoke")
set_tests_properties([=[selfplay_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;151;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
add_test([=[eval_sanity_smoke]=] "/Users/danielding/euclid-engine/build_asan/eval_sanity_smoke")
set_tests_properties([=[eval_sanity_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/danielding/euclid-engine/CMakeLists.txt;155;add_test;/Users/danielding/euclid-engine/CMakeLists.txt;0;")
